framework:
    messenger:
        default_bus: query.bus
        buses:
            query.bus: ~

        transports:
            sync: 'sync://'

        routing:
            'App\Shared\Application\Bus\Query\Query': sync
